//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestDoc.Module.BusinessObjects.postgres
{

    public partial class detail : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>(nameof(id), ref fid, value); }
        }
        string fname;
        [Size(SizeAttribute.Unlimited)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        master fmaster_id;
        [Association(@"detailReferencesmaster")]
        public master master_id
        {
            get { return fmaster_id; }
            set { SetPropertyValue<master>(nameof(master_id), ref fmaster_id, value); }
        }
    }

}
